---
- name : get haproxy url 
  shell : >
    grep -m1 "bind " {{haproxy_config}} | awk '{print $2}'| cut -d ':' -f 1
  register: haproxy_ip_address
  become: true  

- name : get ceilometer password
  shell : >
    grep -m1 "password=" /etc/ceilometer/ceilometer.conf | awk {'print $1'} | cut -d "=" -f 2
  register: ceilometer_password  
  become: true

- name : get ceilometer password
  shell : >
    grep -m1 "password=" /etc/gnocchi/gnocchi.conf | awk {'print $1'} | cut -d "=" -f 2
  register: gnocchi_password  
  become: true



- name: Copy conf files
  template: src=collectd-ceilometer-plugin.conf.j2 dest=/etc/collectd.d/collectd-ceilometer-plugin.conf mode=0644 seuser=unconfined_u force=yes
  become: true


- name: enable collectd systemd service
  service: state=started enabled=yes name=collectd
  become: true

#- name: Copy conf files
#  template: src=collectd-gnocchi-plugin.conf.j2 dest=/etc/collectd.d/collectd-gnocchi-plugin.conf mode=0644 seuser=unconfined_u force=yes
#  become: true